### ISSUE TITLE
Lobby page todo

### ISSUE THREAD

**Issue by ddenizakpinar** [Trendyol/codex#203]
- [ ] Fix incorrect profile images sizes
- [ ] Fix missing default avatars
- [ ] Fix missing user points
- [ ] Fix/Analyze duplicate messages
