### ISSUE TITLE
Room page todo

### ISSUE THREAD

**Issue by ddenizakpinar** [Trendyol/codex#204]
- [ ] Add offline - online user indicator
- [ ] Add user names on cameras
- [ ] Analyze different camera positions
